---

- name: "Install unzip first"
  become: yes
  apt:
    name: unzip
    state: present

- name: "Create temporary directory"
  file: 
    path: /tmp/consul
    state: directory

# - debug: msg="{{ lookup('env', 'GS_ACCESS_KEY_ID')}}"
# - debug: msg="{{ lookup('env', 'GS_SECRET_ACCESS_KEY')}}"

- name: "Download Consul from bucket"
  gc_storage:
    bucket: provision-cloud
    object: consul_1.4.2_linux_amd64.zip
    region: "asia-southeast1"
    dest: "/tmp/consul/consul_1.4.2_linux_amd64.zip"
    mode: get
    gs_access_key: {{ gs_access_key }}
    gs_secret_key: {{ gs_secret_key }}


- name: "Unarchive Consul"
  become: yes
  unarchive:
    src: "/tmp/consul/consul_1.4.2_linux_amd64.zip"
    dest: "/usr/local/bin/"


- name: "Create consul config directory"
  become: yes
  file:
    path: /etc/consul.d
    mode: 0755
    state: directory
    

- name: "Consul configuration"
  become: yes
  template:
    src: "{{ consul_configuration }}"
    dest: /etc/consul.d/consul.json
    mode: 0755

- name: "Consul system service configuration"
  become: "yes"
  template:
    src: "{{ consul_service_configuration }}"
    dest: /etc/systemd/system/consul.service
    mode: 0755

- name: "Start consul via systemd"
  become: yes
  systemd: 
    name: consul
    state: started
    daemon_reload: yes
