---
- name: Install softwares for ubuntu minimal
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - software-properties-common
      - git
      - nano
      - unzip