---

- name: Setup Consul Server
  hosts: localhost
  become: yes
  roles:
    - unzip
    - pip
    - boto
    - consul
  vars:
    bind_ip: 11.11.11.11
    consul_node_name: "consul-server-master"
    consul_dc_name: "angloo-dc"
    consul_service_configuration: consul.server.json.j2
    client_nodes:
      - 10.10.10.10
      - 20.20.20.20
      - 30.30.30.30
      - 40.40.40.40
      - 50.50.50.50