---

- name: play 2
  hosts: localhost
  become: yes
  roles:
    - unzip
    - pip
    - boto
    - consul-server
  vars:
    use_consul: "yes lets use consul"
    bind_ip: "11.11.11.11"
    consul_node_name: "consul-server-master"