---

- name: play wawan
  hosts: bionic2
  become: yes
  # tasks:
  #   - name: Install andrewrothstein consul
  #     command: ansible-galaxy install andrewrothstein.consul
  roles:
    # Note: this roles get from ./roles
    - unzip
    - pip
    - boto
    - consul-client
    # Note: this roles get from ~/.ansible/roles
    # - role: ansible-consul
    # - role: ansible-consul-template
  vars:
    use_consul: "yes lets use consul"
    bind_ip: "11.11.11.13"
    consul_node_name: "client2"
    consul_dc_name: "angloo-dc"