---

- name: play wawan
  hosts: localhost
  become: yes
  # tasks:
  #   - name: Install andrewrothstein consul
  #     command: ansible-galaxy install andrewrothstein.consul
  roles:
    - unzip
    - pip
    - role: andrewrothstein.consul