global:
  scrape_interval:     10s 
  evaluation_interval: 10s

  # external_labels:
      # monitor: 'codelab-monitor'
 
scrape_configs:
  # - job_name: 'node_exporter_staging01'
  #   static_configs:
  #     - targets: ['35.198.210.104:9100']
 
  # - job_name: 'node_exporter_stagi'
  #   static_configs:
  #     - targets: ['35.198.203.224:9100']

  # - job_name: 'node_exporter_webprofileangloo'
  #   static_configs:
  #     - targets: ['35.198.222.168:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: wawan-server-1
    static_configs:
      - targets: ['11.11.11.11:9100']

  - job_name: wawan-client-1
    static_configs:
      - targets: ['11.11.11.12:9100']