APP_NAME="Kosanapp Laravel Img Upload"
APP_ENV=development
APP_KEY=base64:W6ljJSN3TugZZawFUD02qLP4L/wKSzMH2vGoAMCXz+I=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5444
DB_DATABASE={{ key "/angloo/db" }}
DB_USERNAME={{ key "/angloo/db" }}
DB_PASSWORD={{ key "/angloo/db" }}

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=redis
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

KOSAN_BACKEND_HOST=http://192.168.100.118:8000
INTERNAL_API_SECRET=AWWDevKosan201819