---
- name: Php and dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - composer
      - mcrypt
      - php7.2
      - php7.2-cli
      - php7.2-gd
      - php7.2-fpm
      - php7.2-mysql
      - php7.2-mbstring
      - php7.2-xml
      - php7.2-zip
      - php7.2-bcmath
      - php7.2
      - php-curl
