---
- name: Install pip python3
  become: true
  apt:
    name: python3-pip
    update_cache: yes
    state: latest
    
- name: Upgrade pip
  pip: 
    name: pip
    extra_args: --upgrade
# - name: install pip python 2
#   apt:
#     name: python-pip
#     update_cache: yes
#     state: present