---
- name: install pip python3
  apt:
    name: python3-pip
    update_cache: yes
    state: latest

# - name: install pip python 2
#   apt:
#     name: python-pip
#     update_cache: yes
#     state: present