---
- name: Create production directory
  become: yes
  become_user: root
  file:
    path: /var/www/acm
    state: directory
    mode: 'ug+rwx,o+rx'
    owner: jenkins
    group: www-data

- name: Clone production git
  become: yes
  become_user: jenkins
  git: 
    dest: /var/www/acm
    repo: https://gitlab.com/wanfintara/simple-login.git
    # accept_hostkey: true
    force: yes

- name: Make Sure storage is exists and writable
  become: yes
  file:
    path: /var/www/acm/storage
    state: directory

- name: Laravel needs read and write access to the storage and bootstrap/cache folder
  become: yes
  file:
    path: /var/www/acm/storage
    state: directory
    mode: 'ug+rwx,o-w'
    recurse: yes
    group: www-data

- name: Composer Install
  become: yes
  # become_user: jenkins
  composer:
    command: install
    working_dir: '/var/www/acm'
