---
version: '3.7'

services:
 db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hej_wms