global:
  scrape_interval:     10s 
  evaluation_interval: 10s

  # external_labels:
      # monitor: 'codelab-monitor'
 
scrape_configs:

  - job_name: 'wp-angloo-prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: wawan-server-1
    static_configs:
      - targets: ['11.11.11.11:9100']

  - job_name: wawan-client-1
    static_configs:
      - targets: ['11.11.11.12:9100']