---

- name: "Create temporary directory"
  file: 
    path: /tmp/consul
    state: directory

# - debug: msg="{{ lookup('env', 'GS_ACCESS_KEY_ID')}}"
# - debug: msg="{{ lookup('env', 'GS_SECRET_ACCESS_KEY')}}"

- name: "Download Consul Template from bucket"
  gc_storage:
    bucket: provision-cloud
    object: consul-template_0.20.0_linux_amd64.zip
    region: "asia-southeast1"
    dest: "/tmp/consul/consul-template_0.20.0_linux_amd64.zip"
    mode: get
    gs_access_key: "{{ lookup('env', 'GS_ACCESS_KEY_ID') }}"
    gs_secret_key: "{{ lookup('env', 'GS_SECRET_ACCESS_KEY') }}"

- name: Unzip consul template
  become: yes
  unarchive:
    src: /tmp/consul/consul-template_0.20.0_linux_amd64.zip
    dest: /usr/bin

- name: Set permission consul template
  become: yes
  file: 
    path: /usr/bin/consul-template
    mode: "a+x"