---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: dist # equivalent apt-get not aptitude
    update_cache: yes

- name: Remove docker
  become: true
  apt:
    name: docker
    state: absent

- name: Remove docker-engine
  become: true
  apt:
    name: docker-engine
    state: absent

- name: Remove docker.io
  become: true
  apt:
    name: docker.io
    state: absent

- name: Install docker
  become: true
  apt: 
    name: docker.io
    state: latest

- name: Start docker service
  service:
    name: docker
    state: started

# Start docker service on boot
- name: Enable docker service
  service:
    name: docker
    enabled: yes

# ! Ansible need docker compose, docker SDK for python, PyYaml

- name: Install docker compose
  become: true
  apt:
    name: docker-compose
    state: latest

- name: Docker SDK for python
  become: true
  pip:
    name: docker

- name: Install PyYAML
  become: true
  pip:
    name: pyyaml