---
- name: Remove docker
  become: yes
  apt:
    name: "{{ packages }}"
    state: absent
    update_cache: yes
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - docker-compose

- name: Install docker & docker-compose
  become: yes
  apt: 
    name: docker.io
    state: latest

- name: Ensure group "docker" exists
  become: yes
  group:
    name: docker
    state: present

# Add Vagrant user to docker group
- name: Add your "vagrant" to the docker group
  become: yes
  command: "gpasswd -a vagrant docker"

- name: Start docker service
  become: yes
  service:
    name: docker
    state: started

# Start docker service on boot
- name: Enable docker service
  become: yes
  service:
    name: docker
    enabled: yes

# ! Ansible need docker compose, docker SDK for python, PyYaml

- name: Docker SDK for python
  become: yes
  pip:
    name: docker

- name: Docker compose from pip
  become: yes
  pip:
    name: docker-compose

- name: Install PyYAML
  become: yes
  pip:
    name: pyyaml