---
- name: Remove docker
  become: true
  apt:
    name: "{{ packages }}"
    state: absent
    update_cache: yes
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - docker-compose

- name: Install docker & docker-compose
  become: true
  apt: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker.io
      - docker-compose

- name: Start docker service
  service:
    name: docker
    state: started

# Start docker service on boot
- name: Enable docker service
  service:
    name: docker
    enabled: yes

# ! Ansible need docker compose, docker SDK for python, PyYaml

- name: Docker SDK for python
  become: true
  pip:
    name: docker

- name: Install PyYAML
  become: true
  pip:
    name: pyyaml