---

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: dist # equivalent apt-get not aptitude
    update_cache: yes

- name: Remove docker
  become: true
  apt:
    name: docker
    state: absent

- name: Remove docker-engine
  become: true
  apt:
    name: docker-engine
    state: absent

- name: Remove docker.io
  become: true
  apt:
    name: docker.io
    state: absent